services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=hplus2'
      - 'MYSQL_PASSWORD=pass@word1'
      - 'MYSQL_USER=root'
      - 'MYSQL_ROOT_PASSWORD=pass@word1'

    ports:
      - '3307:3306'

  app:
    build: .
    ports:
      - "9099:9099"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: mysql://localhost:3306/hplus2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass@word1

volumes:
  mysql-data:

